import type { Category, Lang, Project } from './types'

export const copy = {
  it: {
    nav: { work: 'Lavori', about: 'Profilo', contact: 'Contatti' },
    eyebrow: 'Film editor · Videomaker · Visual storyteller',
    heroA: 'Le storie',
    heroB: 'trovano ritmo',
    heroC: 'nel montaggio.',
    intro: 'Selezione di immagini, suono e movimento. Un portfolio in forma di sequenza.',
    experience: 'Avvia esperienza',
    index: 'Apri indice',
    selected: 'Lavori selezionati',
    all: 'Tutti',
    view: 'Guarda progetto',
    close: 'Chiudi',
    overview: 'Il progetto',
    contribution: 'Contributo',
    watch: 'Guarda il film',
    aboutLabel: 'Profilo / 00:47',
    aboutTitle: 'Non assemblo semplicemente immagini. Cerco il punto esatto in cui diventano una storia.',
    aboutBody: 'Editor e videomaker con un approccio narrativo al ritmo, al suono e alla composizione. Questo testo è un placeholder pronto per accogliere il profilo definitivo.',
    services: ['Editing', 'Videomaking', 'Music video', 'Film production', 'Social content', 'Visual storytelling'],
    contactLabel: 'Prossima sequenza / 01:12',
    contactTitle: 'Hai una storia che deve trovare il proprio ritmo?',
    contactBody: 'Disponibile per produzioni, brand, artisti e collaborazioni.',
    email: 'Scrivimi',
    footer: 'Portfolio MVP — contenuti dimostrativi',
    modeExperience: 'Experience',
    modeIndex: 'Index',
    menu: 'Menu',
  },
  en: {
    nav: { work: 'Work', about: 'About', contact: 'Contact' },
    eyebrow: 'Film editor · Videomaker · Visual storyteller',
    heroA: 'Stories',
    heroB: 'find their rhythm',
    heroC: 'in the edit.',
    intro: 'A selection of image, sound and movement. A portfolio shaped like a sequence.',
    experience: 'Play experience',
    index: 'Open index',
    selected: 'Selected works',
    all: 'All',
    view: 'View project',
    close: 'Close',
    overview: 'Overview',
    contribution: 'Contribution',
    watch: 'Watch film',
    aboutLabel: 'About / 00:47',
    aboutTitle: 'I do not simply assemble images. I look for the exact point where they become a story.',
    aboutBody: 'Editor and videomaker with a narrative approach to rhythm, sound and composition. This copy is a placeholder ready for the final profile.',
    services: ['Editing', 'Videomaking', 'Music video', 'Film production', 'Social content', 'Visual storytelling'],
    contactLabel: 'Next sequence / 01:12',
    contactTitle: 'Have a story that needs to find its rhythm?',
    contactBody: 'Available for productions, brands, artists and collaborations.',
    email: 'Get in touch',
    footer: 'Portfolio MVP — demonstration content',
    modeExperience: 'Experience',
    modeIndex: 'Index',
    menu: 'Menu',
  },
} satisfies Record<Lang, Record<string, unknown>>

export const categoryLabels: Record<Category, Record<Lang, string>> = {
  music: { it: 'Musica', en: 'Music' },
  social: { it: 'Social', en: 'Social' },
  film: { it: 'Film', en: 'Film' },
  production: { it: 'Grandi produzioni', en: 'Productions' },
}

export const projects: Project[] = [
  {
    slug: 'afterglow',
    number: '01',
    title: 'AFTERGLOW',
    client: 'Aster / Records',
    year: '2026',
    category: 'music',
    roles: ['Editing', 'Color finishing'],
    duration: '03:42',
    featured: true,
    tone: '#df4b2f',
    description: { it: 'Un videoclip costruito su memoria, velocità e luce notturna.', en: 'A music video built around memory, speed and nocturnal light.' },
    statement: { it: 'Tagli netti e pause improvvise trasformano una performance in un ricordo frammentato.', en: 'Hard cuts and sudden pauses turn a performance into a fragmented memory.' },
    video: { provider: 'vimeo', id: '76979871' },
  },
  {
    slug: 'northline',
    number: '02',
    title: 'NORTHLINE',
    client: 'Frame Studio',
    year: '2025',
    category: 'film',
    roles: ['Film editing', 'Sound design'],
    duration: '14:08',
    featured: true,
    tone: '#345f73',
    description: { it: 'Un corto sul paesaggio, la distanza e ciò che resta fuori campo.', en: 'A short film about landscape, distance and what remains outside the frame.' },
    statement: { it: 'Il montaggio lascia respirare lo spazio e usa il suono per suggerire ciò che non vediamo.', en: 'The edit lets the space breathe and uses sound to suggest what we cannot see.' },
    video: { provider: 'youtube', id: 'ScMzIvxBSi4' },
  },
  {
    slug: 'pulse',
    number: '03',
    title: 'PULSE / 15',
    client: 'Mono Brand',
    year: '2026',
    category: 'social',
    roles: ['Editing', 'Motion'],
    duration: '00:15',
    featured: true,
    tone: '#a2ba47',
    description: { it: 'Una campagna verticale rapida, modulare e pensata per il loop.', en: 'A fast, modular vertical campaign designed for the loop.' },
    statement: { it: 'Quindici secondi, una sola idea, nessun fotogramma superfluo.', en: 'Fifteen seconds, one idea, no unnecessary frame.' },
    video: { provider: 'vimeo', id: '76979871' },
  },
  {
    slug: 'monument',
    number: '04',
    title: 'MONUMENT',
    client: 'Northstar Pictures',
    year: '2024',
    category: 'production',
    roles: ['Assistant editing', 'VFX conform'],
    duration: '98:00',
    featured: true,
    tone: '#806b9e',
    description: { it: 'Un progetto corale su scala cinematografica.', en: 'An ensemble project at cinematic scale.' },
    statement: { it: 'Organizzazione invisibile, continuità e precisione al servizio della visione complessiva.', en: 'Invisible organisation, continuity and precision serving the wider vision.' },
    video: { provider: 'youtube', id: 'ScMzIvxBSi4' },
  },
  {
    slug: 'static-bloom',
    number: '05',
    title: 'STATIC BLOOM',
    client: 'Independent',
    year: '2025',
    category: 'music',
    roles: ['Direction', 'Editing'],
    duration: '04:11',
    featured: false,
    tone: '#b04f72',
    description: { it: 'Ritratto musicale tra texture analogiche e dettagli digitali.', en: 'A music portrait between analogue textures and digital detail.' },
    statement: { it: 'La ripetizione diventa linguaggio e crea una tensione crescente.', en: 'Repetition becomes language and builds a growing tension.' },
    video: { provider: 'vimeo', id: '76979871' },
  },
  {
    slug: 'one-more-frame',
    number: '06',
    title: 'ONE MORE FRAME',
    client: 'Personal study',
    year: '2026',
    category: 'social',
    roles: ['Concept', 'Edit'],
    duration: '00:30',
    featured: false,
    tone: '#c78637',
    description: { it: 'Un esperimento breve sul tempo percepito.', en: 'A short experiment about perceived time.' },
    statement: { it: 'Lo stesso gesto cambia significato quando cambia la durata.', en: 'The same gesture changes meaning when its duration changes.' },
    video: { provider: 'youtube', id: 'ScMzIvxBSi4' },
  },
]
